base/api/urls.py
# from django.urls import path
# from . import views
#
# urlpatterns = [
#     path('',  views.getRoutes),
#     path('rooms/', views.getRooms),
#     path('rooms/<str:pk>/', views.getRoom),
# ]

base/urls.py
from django.urls import path
# from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),
    path('register/register2', views.registerPage2, name="register2"),
    path('enterpro', views.enterpro, name="enterpro"),
    path('avatar', views.avatar, name="avatar"),
    path('language/', views.language, name="language"),
    path('languages/', views.languages, name="languages"),
    path('', views.home, name="home"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('update-user/', views.updateUser, name="update-user"),

]

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    lightning_address = models.CharField(max_length=200,unique=True, null=True)
    username = models.CharField(max_length=200, unique=False, null=True)
    dp = models.ImageField(null=True, default="avatar.svg")
    language = models.CharField(max_length=200, null=True)
    nick_name = models.CharField(max_length=200, null=True)


    USERNAME_FIELD = 'lightning_address'
    REQUIRED_FIELDS = []

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms
from django.contrib.auth.forms import PasswordResetForm

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['lightning_address']

class MyUserCreationForm2(UserCreationForm):
    class Meta:
        model = User
        fields = ['nick_name']


class UserForm(ModelForm):
    foot = [
       ('en', ('English')),
       ('esp', ('Spanish')),
       ('fr', ('French')),
        ('it', ('Italian')),
        ('de', ('German')),
   ]

    language = forms.ChoiceField(choices=foot)
    class Meta:
        model = User
        fields = ['dp', 'lightning_address','language', 'nick_name']

class UserForm2(ModelForm):
    class Meta:
        model = User
        fields = ['nick_name']

base/api/views.py
# from rest_framework.decorators import api_view
# from rest_framework.response import Response
# from base.models import Room
# from .serializers import RoomSerializer
# from base.api import serializers
#
#
# @api_view(['GET'])
# def getRoutes(request):
#     routes = [
#         'GET /api',
#         'GET /api/rooms',
#         'GET /api/rooms/:id'
#     ]
#     return Response(routes)
#
#
# @api_view(['GET'])
# def getRooms(request):
#     rooms = Room.objects.all()
#     serializer = RoomSerializer(rooms, many=True)
#     return Response(serializer.data)
#
#
# @api_view(['GET'])
# def getRoom(request, pk):
#     room = Room.objects.get(id=pk)
#     serializer = RoomSerializer(room, many=False)
#     return Response(serializer.data)

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .models import User
from .forms import UserForm,UserForm2, MyUserCreationForm,  MyUserCreationForm2
from .templatetags.languages import translations
import os
# from PIL import Image
# from django.conf import settings
# from .decorators import unauthenticated_user



def loginPage(request):
    page = 'login'
    option = request.session.get('option', 'en')
    if request.method == 'POST':
        lightning_address = request.POST.get('lightning_address').lower()
        password = request.POST.get('password')
        rem = request.POST.get('rem')


        # user = User.objects.get(lightning_address=lightning_address)


        user = authenticate(request, lightning_address=lightning_address, password=password)
        if user is None:
            # text = ['Invalid details']
            # return render(request, 'base/loginerr.html', {'text': text, 'option': option})
            messages.error(request, 'Invalid credentials')
        else:
            login(request, user)
            if not rem:
                request.session.set_expiry(0)
            else:
                request.session.set_expiry(None)
            messages.success(request, 'Login Successful')
            login(request, user)

            return redirect('enterpro')


    context = {'page': page, 'option': option}

    return render(request, 'base/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home')

def registerPage(request):
    option = request.session.get('option', 'en')
    form = MyUserCreationForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            request.session['lightning_address'] = form.cleaned_data['lightning_address']
            request.session['password1'] = form.cleaned_data['password1']
            request.session['password2'] = form.cleaned_data['password2']
            return redirect('register2')
        else:
            text = ["Invalid Credentials"]
            return render(request, 'base/loginerr.html', {'text': text, 'option': option})
    return render(request, 'base/register.html', {'form':form, 'option': option})


def registerPage2(request):
    option = request.session.get('option', 'en')
    form = MyUserCreationForm2(request.POST)
    if request.method == 'POST':
        nickname = request.POST.get('nick_name')
        lightning_address = request.session.get('lightning_address')
        password1 = request.session.get('password1')
        password2 = request.session.get('password2')
        user = User.objects.create_user(nick_name=nickname, username=lightning_address,
                    lightning_address=lightning_address, language=option,
                    password=password1)
        user.save()
        return redirect('login')
    return render(request, 'base/register2.html', {'form': form, 'option': option})


def home(request):
    option = request.session.get('option', 'en')
    return render(request, 'base/The solution-Get Started.html', {'option': option})

def language(request):
    option = request.session.get('option', 'en')
    if request.method == 'POST':
        option = request.POST.get('selectedvalue', 'en')
        request.session['option'] = option
        return redirect('home')
    return render(request, 'base/Language.html', {'option': option})

def languages(request):
    if request.method == 'POST':
        user = request.user
        option = request.POST.get('selectedvalue')
        user.language = option
        user.save()
        return redirect('languages')
    return render(request, 'base/Language2.html',)

def avatar(request):
    if request.method == 'POST':
        user = request.user
        option = request.POST.get('selected_option')
        user.dp = option
        user.save()
        messages.success(request, 'Avatar updated Successfully')
        return redirect('update-user')
    return render(request, 'base/avatar.html', {})

@login_required(login_url='login')
def userProfile(request, pk):
    user = User.objects.get(id=pk)
    context = {'user':user}
    return render(request, 'base/Profile Logout.html', context)

@login_required(login_url='login')
def enterpro(request):
    return render(request, 'base/enterpro.html')

@login_required(login_url='login')
def updateUser(request):
    if request.method == 'POST':
        user = request.user
        nn = request.POST.get('nick_name')
        user.nick_name = nn
        user.save()
        messages.success(request, 'Profile updated Successfully')
        return redirect('update-user')


    return render(request, 'base/Update Profile.html')

base/templates/base/Language.html
{% extends 'base/The solution-Get Started.html' %}
{% load languages %}
{% load static %}
{% block content %}
  <body>
    <div id="root">
      <div class="mx-auto max-w-[200rem]">
        <div class="min-h-screen  items-center justify-center bg-appDarkBlue100 md:flex">
          <main class="app-container flex min-h-screen flex-col text-white md:min-h-max ">
            <header class="mb-11 pt-12">
              <a href="{% url 'home' %}"><button type="button" class="flex items-center gap-x-2 text-base font-medium md:text-lg lg:text-xl">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="text-2xl md:text-3xl lg:text-4xl iconify iconify--ion" width="1em" height="1em" viewBox="0 0 512 512">
                <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M244 400L100 256l144-144M120 256h292"></path>
              </svg><span>{{"Back"|new_translate:option}}</span></button></a>
            </header>
            <h1 class="text-2xl font-semibold md:text-3xl lg:text-4xl">
                {{"What is your language"|new_translate:option}}</h1>
            <p class="pb-6 pt-3 text-sm font-normal sm:text-base">
                {{"Select a language to get started"|new_translate:option}}</p>
            <form method="post" id="myForm" action="">
                {% csrf_token %}
            <ul class="flex flex-1 flex-col gap-y-2" id="list">
              <li data-value="en" class="flex cursor-pointer items-center rounded-lg border-[2px] border-appGray100 px-3 py-4 text-sm font-semibold transition-all duration-300 sm:text-base">
            <img src="{% static 'svg/en.svg' %}">
          {{"en"|new_translate:option}}

          </li>
          <li data-value="esp" class="flex cursor-pointer items-center rounded-lg border-[2px] border-appGray100 px-3 py-4 text-sm font-semibold transition-all duration-300 sm:text-base">
          <img src="{% static 'svg/esp.svg' %}"> {{"esp"|new_translate:option}}</li>
        <li data-value="fr" class="flex cursor-pointer items-center rounded-lg border-[2px] border-appGray100 px-3 py-4 text-sm font-semibold transition-all duration-300 sm:text-base">
          <img src="{% static 'svg/fr.svg' %}">{{"fr"|new_translate:option}}</li></ul>
        <input type="hidden" id="selectedValue" name="selectedvalue"/>
        <div id="submitBtn" class="py-6 md:pt-12"><button class="app-button-primary block text-center">{{"Confirm"|new_translate:option}}</button></div>
      </form></main></div></div></div>
  </body>
 <script>
// Get the list element
var list = document.getElementById("list");

// Add click event listeners to list items
list.addEventListener("click", function(event) {
  var selectedValue = event.target.getAttribute("data-value");

  // Remove existing selected class from all list items
  var items = list.getElementsByTagName("li");
  for (var i = 0; i < items.length; i++) {
    items[i].classList.remove("selected");
  }

  // Add selected class to the clicked item
  event.target.classList.add("selected");

  // Set the value of the hidden input field
  document.getElementById("selectedValue").value = selectedValue;
});

</script>

<style>
  .selected {
    background-color: #0072fb;
  }
  img{
    margin-right: 15px;
  }
</style>



{% endblock content %}

base/templates/base/Language2.html
{% extends 'base/The solution-Get Started.html' %}
{% load languages %}
{% load static %}
{% block content %}
  <body>
    <div id="root">
      <div class="mx-auto max-w-[200rem]">
        <div class="min-h-screen  items-center justify-center bg-appDarkBlue100 md:flex">
          <main class="app-container flex min-h-screen flex-col text-white md:min-h-max ">
            <header class="mb-11 pt-12">
              <a href="{% url 'user-profile' user.id %}"><button type="button" class="flex items-center gap-x-2 text-base font-medium md:text-lg lg:text-xl">
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="text-2xl md:text-3xl lg:text-4xl iconify iconify--ion" width="1em" height="1em" viewBox="0 0 512 512">
                <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M244 400L100 256l144-144M120 256h292"></path>
              </svg><span>{{"Back"|translate:request.user.id}}</span></button></a>
            </header>
            <h1 class="text-2xl font-semibold md:text-3xl lg:text-4xl">
                {{"What is your language"|translate:request.user.id}}</h1><br>
            <!--<p class="pb-6 pt-3 text-sm font-normal sm:text-base">-->
            <!--    {{"Select a language to get started"|translate:request.user.id}}</p>-->
            <form method="post" id="myForm" action="">
                {% csrf_token %}
            <ul class="flex flex-1 flex-col gap-y-2" id="list">
              <li data-value="en" class="flex cursor-pointer items-center rounded-lg border-[2px] border-appGray100 px-3 py-4 text-sm font-semibold transition-all duration-300 sm:text-base">
            <img src="{% static 'svg/en.svg' %}">
          {{"en"|translate:request.user.id}}

          </li>
          <li data-value="esp" class="flex cursor-pointer items-center rounded-lg border-[2px] border-appGray100 px-3 py-4 text-sm font-semibold transition-all duration-300 sm:text-base">
          <img src="{% static 'svg/esp.svg' %}"> {{"esp"|translate:request.user.id}}</li>
        <li data-value="fr" class="flex cursor-pointer items-center rounded-lg border-[2px] border-appGray100 px-3 py-4 text-sm font-semibold transition-all duration-300 sm:text-base">
          <img src="{% static 'svg/fr.svg' %}">{{"fr"|translate:request.user.id}}</li></ul>
        <input type="hidden" id="selectedValue" name="selectedvalue"/>
        <div id="submitBtn" class="py-6 md:pt-12"><button class="app-button-primary block text-center">{{"Confirm"|translate:request.user.id}}</button></div>
      </form></main></div></div></div>
  </body>
 <script>
// Get the list element
var list = document.getElementById("list");

// Add click event listeners to list items
list.addEventListener("click", function(event) {
  var selectedValue = event.target.getAttribute("data-value");

  // Remove existing selected class from all list items
  var items = list.getElementsByTagName("li");
  for (var i = 0; i < items.length; i++) {
    items[i].classList.remove("selected");
  }

  // Add selected class to the clicked item
  event.target.classList.add("selected");

  // Set the value of the hidden input field
  document.getElementById("selectedValue").value = selectedValue;
});

</script>

<style>
  .selected {
    background-color: #0072fb;
  }
  img{
    margin-right: 15px;
  }
</style>



{% endblock content %}

base/templates/base/Update Profile.html
{% extends 'base/The solution-Get Started.html' %}
{% load languages %}
{% load static %}
{% block content %}


<div id="root">
<div class="mx-auto max-w-[200rem]">
<div class=" min-h-screen flex-col items-center justify-center bg-appBlue100 sm:flex">
<div class="w-full sm:hidden">
<div class="flex min-h-screen flex-col">
        <main class="flex flex-1 flex-col bg-appDarkBlue100 px-6 pt-8 text-white">
        <div class="pt-4">
       <a href="{% url 'user-profile' user.id %}"> <button class="hover:text-appYellow100 absolute flex items-center gap-x-2 transition-all duration-300">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class=" text-xl md:text-2xl lg:text-3xl iconify iconify--ion" width="1em" height="1em" viewBox="0 0 512 512">
        <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M244 400L100 256l144-144M120 256h292">
        </path>
        </svg>
        <span class="text-base font-semibold md:text-lg lg:text-xl">{{"Back"|translate:request.user.id}}
        </span>
        </button></a>
        </div>
        <div class="pt-14 sm:hidden">
        <img src="/static/images/{{user.dp}}" class="mx-auto aspect-square w-40 rounded-full object-contain" alt="Avatar">
        </div>
        <div class="flex items-center pt-2">
        <button class="mx-auto w-full max-w-[12.25rem] rounded-2xl bg-appGreen300 p-2 shadow-appButtonInnerShadow">
            <a href="{% url 'avatar' %}">{{"Change Avatar"|translate:request.user.id}}</a>
       </button>
        </div>
        <label class="mb-2 mt-7 block text-sm text-appGray400 sm:text-base">{{"Nick name"|translate:request.user.id}}
        </label>

        <div>
        <form method="POST" action="">
              {% csrf_token %}
        <input type="text" name="nick_name" class="w-full rounded-2xl bg-white p-4 text-base text-appBlue100 outline-0" value="{{user.nick_name}}">

        <label class="mb-2 mt-5 block text-sm text-appGray400 sm:text-base">{{"Lightning address"|translate:request.user.id}}
        </label>
        <div class="rounded-2xl bg-appGray600 px-4 py-4 text-sm font-normal text-appGray500 sm:text-base">{{user.lightning_address}}
        </div>
        <button type="submit" class="app-button-primary mt-8 sm:mb-10">{{"Update Profile"|translate:request.user.id}}
        </button>

        </form>
        </div>
        </main>
</div>
</div>
<div class="hidden w-full  sm:block">
        <main class="bg-appBlue800 mx-auto w-full max-w-[31.813rem] rounded-2xl px-8 py-4 text-white ">
        <header class="relative flex items-center justify-between py-5">
       <a href="{% url 'user-profile' user.id %}"> <button class="hover:text-appYellow100 absolute flex items-center gap-x-2 transition-all duration-300">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class=" text-xl md:text-2xl lg:text-3xl iconify iconify--ion" width="1em" height="1em" viewBox="0 0 512 512">
        <path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M244 400L100 256l144-144M120 256h292">
        </path>
        </svg>
        <span class="text-base font-semibold md:text-lg lg:text-xl">{{"Back"|translate:request.user.id}}
        </span>
       </button></a>
        <p class="flex-1 text-center text-base font-bold md:text-lg lg:text-xl">{{"Edit profile"|translate:request.user.id}}
        </p>
        </header>
        <img class="mx-auto aspect-square  w-full max-w-[7rem] rounded-full bg-appBlue100 object-contain" src="/static/images/{{user.dp}}" alt="Avatar">
        <div class="pt-14 sm:hidden">
        <img src="FEL.JPG" class="mx-auto aspect-square w-40 rounded-full object-contain" alt="">
        </div>
        <div class="flex items-center pt-2">
        <button class="mx-auto w-full max-w-[12.25rem] rounded-2xl bg-appGreen300 p-2 shadow-appButtonInnerShadow">
            <a href="{% url 'avatar' %}">{{"Change Avatar"|translate:request.user.id}}</a>
        </button>
        </div>
        <label class="mb-2 mt-7 block text-sm text-appGray400 sm:text-base">{{"Nick name"|translate:request.user.id}}
        </label>

        <div>
        <form method="POST" action="">
              {% csrf_token %}
        <input type="text" name="nick_name" class="w-full rounded-2xl bg-white p-4 text-base text-appBlue100 outline-0" value="{{user.nick_name}}">

        <label class="mb-2 mt-5 block text-sm text-appGray400 sm:text-base">{{"Lightning address"|translate:request.user.id}}
        </label>
        <div class="rounded-2xl bg-appGray600 px-4 py-4 text-sm font-normal text-appGray500 sm:text-base">{{user.lightning_address}}
        </div>
        <button type="submit" class="app-button-primary mt-8 sm:mb-10">{{"Update Profile"|translate:request.user.id}}
        </button>
          </form>
          </div>
        </main>
</div>
</div>
</div>
</div>


{% endblock content %}

base/templates/base/login.html
{% extends 'base/The solution-Get Started.html' %}
{% load languages %}
{% block content %}

<body>
   <div id="root"><div class="mx-auto max-w-[200rem]">
       <div class="min-h-screen  items-center justify-center bg-appDarkBlue100 md:flex">
           <main class="app-container flex min-h-screen flex-col text-white md:min-h-max ">
               <header class="mb-11 pt-12">
                  <a href="{% url 'home' %}"> <button type="button" class="flex items-center gap-x-2 text-base font-medium md:text-lg
                   lg:text-xl">
                   <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="text-2xl md:text-3xl lg:text-4xl iconify iconify--ion" width="1em" height="1em" viewBox="0 0 512 512"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="48" d="M244 400L100 256l144-144M120 256h292">

                   </path>
                   </svg>
                   <span>{{"Back"|new_translate:option}}</span>
                </button></a>
               </header>
               <h1 class="mb-6 pr-1 text-2xl font-semibold md:text-3xl lg:text-4xl">{{"Welcome Back"|new_translate:option}},</h1>
               <form class="flex flex-1 flex-col justify-between" action="" method="POST">
                   {% csrf_token %}
                   <div class="flex flex-col gap-y-4">
                   <div><div class="focus-within:bg-appDarkBlue200 focus-within:border-appBlue500 flex items-center gap-x-2 rounded-lg border border-transparent bg-appGray100 px-4 transition-all duration-300"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="text-xl sm:text-2xl iconify iconify--emojione-v1" width="1em" height="1em" viewBox="0 0 64 64"><path fill="#fbb11c" d="M43.4.159L12.06 28.492l24.31 7.538L18.12 64l35.26-33.426l-18.978-8.464z"></path></svg>

    <input class="placeholder:text-appGray200 w-full bg-transparent py-4 text-white outline-0" placeholder="{{'Lightning address'|new_translate:option}}" name="lightning_address" maxlength="200" autofocus required id="id_lightning_address"></div>
           </div><div><div class="focus-within:bg-appDarkBlue200 focus-within:border-appBlue500 flex items-center gap-x-2 rounded-lg border border-transparent bg-appGray100 px-4 transition-all duration-300"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="text-xl sm:text-2xl iconify iconify--mdi" width="1em" height="1em" viewBox="0 0 24 24"><path fill="currentColor" d="M12 17a2 2 0 0 1-2-2c0-1.11.89-2 2-2a2 2 0 0 1 2 2a2 2 0 0 1-2 2m6 3V10H6v10zm0-12a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V10c0-1.11.89-2 2-2h1V6a5 5 0 0 1 5-5a5 5 0 0 1 5 5v2zm-6-5a3 3 0 0 0-3 3v2h6V6a3 3 0 0 0-3-3"></path></svg>

      <input class="placeholder:text-appGray200 w-full bg-transparent py-4 text-white outline-0"
             placeholder="{{'Password'|new_translate:option}}" required name="password" autocomplete="new-password"
             id="password1" type="password"><span class="password-toggle-icon">
                       <i class="fas fa-eye"></i></span></div>
               </div><div>

                       <div class="my-6 flex items-center justify-between">
        <button type="button" class="flex items-center gap-3 text-sm font-normal sm:text-base">
     <input type="checkbox" name="rem">
        <span>{{'Remember me'|new_translate:option}}
        </span>
        </button>
        <a class="text-sm font-semibold text-white transition-all duration-300 hover:text-appYellow100 sm:text-base" href="">{{'Forgot Password'|new_translate:option}}
        </a>
        </div>
      <button type="submit" class="app-button-primary">{{'Sign in'|new_translate:option}}</button>
               </div><div class="flex flex-1 flex-col justify-end py-10 md:pt-32"><p class="text-center text-sm font-medium sm:text-base">
                  {{' Don’t have an account yet?'|new_translate:option}}
                   <a class="px-2 font-bold transition-all duration-300 hover:text-appYellow100" href="{% url 'register' %}">
                       Sign up</a></p></div></main></div></div></div>
  </body>
  <script src="scrip.js"></script>

  <script type="text/javascript">
    const passwordField = document.getElementById("password1");
const togglePassword = document.querySelector(".password-toggle-icon i");

togglePassword.addEventListener("click", function () {
  if (passwordField.type === "password") {
    passwordField.type = "text";
    togglePassword.classList.remove("fa-eye-slash");
    togglePassword.classList.add("fa-eye");
  } else {
    passwordField.type = "password";
    togglePassword.classList.remove("fa-eye");
    togglePassword.classList.add("fa-eye-slash");
  }
});

</script>


{% endblock content %}

base/templates/base/loginerr.html

{% load languages %}
{% block content %}
<h3 style="text-align:center; color: red;"><br><br>Error</h3><br><hr>
<h1 style="text-align:center; color: #71c6dd;"><br><br>{% for text in text %}
     <li>{{text|safe|new_translate:option}}</li><br><br>
{% endfor %}
</h1><br>

    {% endblock %}

<style>

* {
  font-family: "DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans",
    "Helvetica Neue", sans-serif;
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  text-rendering: optimizeLegibility;
  /* color: inherit; */
  font-size: inherit;
}

html {
  font-size: 56.25%;
}

@media only screen and (min-width: 1200px) {
  html {
    font-size: 62.5%;
  }
}

@media only screen and (min-width: 2100px) {
  html {
    font-size: 75%;
  }
}

    body {
  line-height: 1.6;
  font-weight: 400;
  font-size: 1.5rem;
  color: var(--color-light-gray);
  background-color: #2d2d39;
  min-height: 100vh;
}

</style>

base/templates/base/password_reset.html

{% extends 'base/login.html' %}
{% load languages %}
{% block content %}

          <div class="layout__body"><br>

            <h1 class="auth__tagline">{{'Password reset'|translate:request.user.id}}</h1>
              <div class="form__group">
                <p>{{'Forgotten your password? Enter your email address below, and we will email instructions for setting a new one.'|translate:request.user.id}}</p>
             </div>
              <form class="form" action="" method="POST">
              {% csrf_token %}
              {% for field in form %}
          <div class="form__group form__group">
            <label style="text-align:left">{{"Email address"|translate:request.user.id}}</label>
              <div >{{field}}</div>

          </div>
          {% endfor %}
               <div class="auth__action">
            <input class="btn--main" type="submit" value="{{'Continue'|translate:request.user.id}}" />

            </div>

            </form>
          </div>

{% endblock content %}

base/templates/base/password_reset_done.html


{% extends 'base/login.html' %}
{% load languages %}
{% block content %}

          <div class="layout__body"><br>

            <h1 class="auth__tagline">{{'Password reset complete'|translate:request.user.id}}</h1>
              <div class="form__group">
                <p>{{'Your password has been set. You may go ahead and log in now.'|translate:request.user.id}}</p>

             </div>
              <div class="auth__action">
              <p>
              <a href="{% url 'login' %}" class="btn btn--link">{{"Log in"|translate:request.user.id}}</a></p>

            </div>
          </div>
      {% endblock content %}